#!/bin/sh

# CUSTOM SMART ALIASES
set_custom_alias() {
  cmd_name=$1
  cmd_alias=$2
  cmd_alias_options=$3
  if type "${cmd_alias}" > /dev/null; then
    alias ${cmd_name}="${cmd_alias} ${cmd_alias_options}"
  fi
}

set_custom_alias "ll" "ls" "-lha"
set_custom_alias "ssh" "autossh"

# EXTRA RC FILES NOT UPLOADED TO GITHUB
dot_files_rc_dir=~/dot-files/rc
if [ -d "$dot_files_rc_dir" ]; then
  rc_files=`find $dot_files_rc_dir -name "*" -type f -print`
  for f in $rc_files; do source $f; done
fi

unset rc_files
unset dot_files_rc_dir
unset -f set_custom_alias

export PATH=~/bin:/usr/local/bin:/usr/local/sbin:$PATH

