#!/bin/sh

# CUSTOM SMART ALIASES
set_custom_alias() {
  cmd_name=$1
  cmd_alias=$2
  cmd_alias_options=$3
  if type "${cmd_alias}" > /dev/null; then
    alias ${cmd_name}="${cmd_alias} ${cmd_alias_options}"
  fi
}

set_custom_alias "ll" "ls" "-lhA"
set_custom_alias "ssh" "autossh"
alias historyg='history | grep $@'
alias hsg='history | grep $@'
alias psg='ps -fea | grep $@'

# EXTRA RC FILES NOT UPLOADED TO GITHUB
dot_files_rc_dir=~/dot-files/rc
if [ -d "$dot_files_rc_dir" ]; then
  for f in `ls $dot_files_rc_dir`; do
    rc_file="$dot_files_rc_dir/$f"
    if [ -f "$rc_file" ]; then source $rc_file; fi
  done
fi

unset rc_file
unset dot_files_rc_dir
unset -f set_custom_alias

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "$HOME/.gvm/bin/gvm-init.sh" ]] && source "$HOME/.gvm/bin/gvm-init.sh"

export_to_path() {
  bin_path=$1
  [[ -d "${bin_path}" ]] && export PATH=${bin_path}:$PATH
}

npm_bin_pat=h/usr/local/share/npm/bin
export_to_path "/usr/local/share/npm/bin"
export_to_path "/usr/local/bin"
export_to_path "/usr/local/sbin"
unset -f export_to_path

export PATH=~/bin:$PATH

